name: Release please

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write
  pull-requests: write

jobs:
  release-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Release with release-please
        uses: google-github-actions/release-please-action@a2d8d683f209466ee8c695cd994ae2cf08b1642d #4.0.1
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: simple